Hotfix setup
SantanderMetGroup/WRF4G pull request #33
Opened 2021-02-06 00:47 UTC by fernanqv

Several bugs fixed

2021-02-06 08:49 UTC, cofinoa commented
The `setup.py` still has prints from version 2. Lines 56 and 58


Uptade lines 21 and 22 (probably these lines needs to be updated in the whole code)
```
__version__  = '2.3.1'
__author__   = 'Valvanuz Fernández, Jesus Fernandez, Carlos Blanco and Antonio S. Cofiño'
```
Update lines 82 and 84,
```
version=__version__,
author_email='meteo@unican.es',
```

2021-02-09 17:51 UTC, cofinoa requested changes

2021-02-09 17:51 UTC, cofinoa commented on setup.py
> +    version='__version__',
remove quotes

2021-02-12 13:51 UTC, fernanqv commented
Done!

2021-02-12 15:19 UTC, cofinoa approved these changes

2021-02-12 15:20 UTC, merged